<?php

/**
 * This is the model base class for the table "apartamento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Apartamento".
 *
 * Columns in table "apartamento" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idApartamento
 * @property string $Direccion
 * @property integer $Tipo
 * @property integer $Tamaño
 * @property integer $numBaños
 * @property integer $numHab
 * @property integer $Sala
 * @property integer $Cocina
 * @property integer $Comedor
 * @property integer $numEst
 * @property integer $Maletero
 * @property integer $Casillero
 * @property integer $Alícuota
 *
 */
abstract class BaseApartamento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'apartamento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Apartamento|Apartamentos', $n);
	}

	public static function representingColumn() {
		return 'Direccion';
	}

	public function rules() {
		return array(
			array('Direccion, Tipo, Tamaño, numBaños, numHab, Sala, Cocina, Comedor, numEst, Maletero, Casillero, Alícuota', 'required'),
			array('Tipo, Tamaño, numBaños, numHab, Sala, Cocina, Comedor, numEst, Maletero, Casillero, Alícuota', 'numerical', 'integerOnly'=>true),
			array('Direccion', 'length', 'max'=>20),
			array('idApartamento, Direccion, Tipo, Tamaño, numBaños, numHab, Sala, Cocina, Comedor, numEst, Maletero, Casillero, Alícuota', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idApartamento' => Yii::t('app', 'Id Apartamento'),
			'Direccion' => Yii::t('app', 'Direccion'),
			'Tipo' => Yii::t('app', 'Tipo'),
			'Tamaño' => Yii::t('app', 'Tama�o'),
			'numBaños' => Yii::t('app', 'Num Ba�os'),
			'numHab' => Yii::t('app', 'Num Hab'),
			'Sala' => Yii::t('app', 'Sala'),
			'Cocina' => Yii::t('app', 'Cocina'),
			'Comedor' => Yii::t('app', 'Comedor'),
			'numEst' => Yii::t('app', 'Num Est'),
			'Maletero' => Yii::t('app', 'Maletero'),
			'Casillero' => Yii::t('app', 'Casillero'),
			'Alícuota' => Yii::t('app', 'Al�cuota'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idApartamento', $this->idApartamento);
		$criteria->compare('Direccion', $this->Direccion, true);
		$criteria->compare('Tipo', $this->Tipo);
		$criteria->compare('Tamaño', $this->Tamaño);
		$criteria->compare('numBaños', $this->numBaños);
		$criteria->compare('numHab', $this->numHab);
		$criteria->compare('Sala', $this->Sala);
		$criteria->compare('Cocina', $this->Cocina);
		$criteria->compare('Comedor', $this->Comedor);
		$criteria->compare('numEst', $this->numEst);
		$criteria->compare('Maletero', $this->Maletero);
		$criteria->compare('Casillero', $this->Casillero);
		$criteria->compare('Alícuota', $this->Alícuota);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}