<?php

/**
 * This is the model base class for the table "gasto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gasto".
 *
 * Columns in table "gasto" available as properties of the model,
 * followed by relations of table "gasto" available as properties of the model.
 *
 * @property integer $idGasto
 * @property string $Nombre
 * @property string $Descripcion
 *
 * @property GastoHistorial[] $gastoHistorials
 */
abstract class BaseGasto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gasto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gasto|Gastos', $n);
	}

	public static function representingColumn() {
		return 'Nombre';
	}

	public function rules() {
		return array(
			array('Nombre', 'required'),
			array('Nombre', 'length', 'max'=>30),
			array('Descripcion', 'length', 'max'=>1000),
			array('Descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idGasto, Nombre, Descripcion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'gastoHistorials' => array(self::HAS_MANY, 'GastoHistorial', 'idGasto'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idGasto' => Yii::t('app', 'Id Gasto'),
			'Nombre' => Yii::t('app', 'Nombre'),
			'Descripcion' => Yii::t('app', 'Descripcion'),
			'gastoHistorials' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idGasto', $this->idGasto);
		$criteria->compare('Nombre', $this->Nombre, true);
		$criteria->compare('Descripcion', $this->Descripcion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}