<?php

/**
 * This is the model base class for the table "apartamento_usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ApartamentoUsuario".
 *
 * Columns in table "apartamento_usuario" available as properties of the model,
 * followed by relations of table "apartamento_usuario" available as properties of the model.
 *
 * @property integer $idusuarioapartamento
 * @property integer $idusuario
 * @property integer $idapartamento
 *
 * @property Apartamento $idapartamento0
 * @property Usuario $idusuario0
 */
abstract class BaseApartamentoUsuario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'apartamento_usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ApartamentoUsuario|ApartamentoUsuarios', $n);
	}

	public static function representingColumn() {
		return 'idusuarioapartamento';
	}

	public function rules() {
		return array(
			array('idusuario, idapartamento', 'required'),
			array('idusuario, idapartamento', 'numerical', 'integerOnly'=>true),
			array('idusuarioapartamento, idusuario, idapartamento', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idapartamento0' => array(self::BELONGS_TO, 'Apartamento', 'idapartamento'),
			'idusuario0' => array(self::BELONGS_TO, 'Usuario', 'idusuario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idusuarioapartamento' => Yii::t('app', 'Idusuarioapartamento'),
			'idusuario' => null,
			'idapartamento' => null,
			'idapartamento0' => null,
			'idusuario0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idusuarioapartamento', $this->idusuarioapartamento);
		$criteria->compare('idusuario', $this->idusuario);
		$criteria->compare('idapartamento', $this->idapartamento);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}