<?php

/**
 * This is the model base class for the table "publicacion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Publicacion".
 *
 * Columns in table "publicacion" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $titulo
 * @property string $contenido
 *
 */
abstract class BasePublicacion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'publicacion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Publicacion|Publicacions', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('titulo, contenido', 'required'),
			array('titulo', 'length', 'max'=>50),
			array('id, titulo, contenido', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'titulo' => Yii::t('app', 'Titulo'),
			'contenido' => Yii::t('app', 'Contenido'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('contenido', $this->contenido, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}