<?php

/**
 * This is the model base class for the table "gasto_fecha".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GastoFecha".
 *
 * Columns in table "gasto_fecha" available as properties of the model,
 * followed by relations of table "gasto_fecha" available as properties of the model.
 *
 * @property integer $idGastoFecha
 * @property string $Fecha
 *
 * @property GastoHistorial[] $gastoHistorials
 */
abstract class BaseGastoFecha extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gasto_fecha';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GastoFecha|GastoFechas', $n);
	}

	public static function representingColumn() {
		return 'Fecha';
	}

	public function rules() {
		return array(
			array('Fecha', 'required'),
			array('idGastoFecha, Fecha', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'gastoHistorials' => array(self::HAS_MANY, 'GastoHistorial', 'idGastoFecha'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idGastoFecha' => Yii::t('app', 'Id Gasto Fecha'),
			'Fecha' => Yii::t('app', 'Fecha'),
			'gastoHistorials' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idGastoFecha', $this->idGastoFecha);
		$criteria->compare('Fecha', $this->Fecha, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}