<?php

/**
 * This is the model base class for the table "gasto_entidad_historial".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GastoEntidadHistorial".
 *
 * Columns in table "gasto_entidad_historial" available as properties of the model,
 * followed by relations of table "gasto_entidad_historial" available as properties of the model.
 *
 * @property integer $idEntidadHistorial
 * @property integer $idGastoHistorial
 * @property integer $idEdificio
 * @property integer $idApartamento
 * @property integer $NroDePiso
 *
 * @property Apartamentos $idApartamento0
 * @property GastoHistorial $idGastoHistorial0
 * @property Edificio $idEdificio0
 */
abstract class BaseGastoEntidadHistorial extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gasto_entidad_historial';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GastoEntidadHistorial|GastoEntidadHistorials', $n);
	}

	public static function representingColumn() {
		return 'idEntidadHistorial';
	}

	public function rules() {
		return array(
			array('idGastoHistorial, idEdificio, idApartamento, NroDePiso', 'required'),
			array('idGastoHistorial, idEdificio, idApartamento, NroDePiso', 'numerical', 'integerOnly'=>true),
			array('idEntidadHistorial, idGastoHistorial, idEdificio, idApartamento, NroDePiso', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idApartamento0' => array(self::BELONGS_TO, 'Apartamentos', 'idApartamento'),
			'idGastoHistorial0' => array(self::BELONGS_TO, 'GastoHistorial', 'idGastoHistorial'),
			'idEdificio0' => array(self::BELONGS_TO, 'Edificio', 'idEdificio'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idEntidadHistorial' => Yii::t('app', 'Id Entidad Historial'),
			'idGastoHistorial' => null,
			'idEdificio' => null,
			'idApartamento' => null,
			'NroDePiso' => Yii::t('app', 'Nro De Piso'),
			'idApartamento0' => null,
			'idGastoHistorial0' => null,
			'idEdificio0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idEntidadHistorial', $this->idEntidadHistorial);
		$criteria->compare('idGastoHistorial', $this->idGastoHistorial);
		$criteria->compare('idEdificio', $this->idEdificio);
		$criteria->compare('idApartamento', $this->idApartamento);
		$criteria->compare('NroDePiso', $this->NroDePiso);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}