<?php

/**
 * This is the model base class for the table "pagos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pagos".
 *
 * Columns in table "pagos" available as properties of the model,
 * followed by relations of table "pagos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idusuario
 * @property integer $monto
 * @property integer $idtipo
 * @property integer $nro_referencia
 * @property integer $idbanco
 * @property string $fecha
 * @property integer $idEstado
 *
 * @property PagosEstados $idEstado0
 * @property PagosTipos $idtipo0
 * @property PagosBancos $idbanco0
 * @property Usuario $idusuario0
 */
abstract class BasePagos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pagos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pagos|Pagoses', $n);
	}

	public static function representingColumn() {
		return 'fecha';
	}

	public function rules() {
		return array(
			array('idusuario, monto, idtipo, nro_referencia, idbanco, fecha', 'required'),
			array('idusuario, monto, idtipo, nro_referencia, idbanco, idEstado', 'numerical', 'integerOnly'=>true),
			array('idEstado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idusuario, monto, idtipo, nro_referencia, idbanco, fecha, idEstado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idEstado0' => array(self::BELONGS_TO, 'PagosEstados', 'idEstado'),
			'idtipo0' => array(self::BELONGS_TO, 'PagosTipos', 'idtipo'),
			'idbanco0' => array(self::BELONGS_TO, 'PagosBancos', 'idbanco'),
			'idusuario0' => array(self::BELONGS_TO, 'Usuario', 'idusuario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idusuario' => null,
			'monto' => Yii::t('app', 'Monto'),
			'idtipo' => null,
			'nro_referencia' => Yii::t('app', 'Nro Referencia'),
			'idbanco' => null,
			'fecha' => Yii::t('app', 'Fecha'),
			'idEstado' => null,
			'idEstado0' => null,
			'idtipo0' => null,
			'idbanco0' => null,
			'idusuario0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idusuario', $this->idusuario);
		$criteria->compare('monto', $this->monto);
		$criteria->compare('idtipo', $this->idtipo);
		$criteria->compare('nro_referencia', $this->nro_referencia);
		$criteria->compare('idbanco', $this->idbanco);
		$criteria->compare('fecha', $this->fecha, true);
		$criteria->compare('idEstado', $this->idEstado);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}