<?php

/**
 * This is the model base class for the table "opcionhorario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Opcionhorario".
 *
 * Columns in table "opcionhorario" available as properties of the model,
 * followed by relations of table "opcionhorario" available as properties of the model.
 *
 * @property integer $idOpcionHorario
 * @property string $Hora
 * @property integer $idHorarioSeleccion
 * @property string $Fecha
 *
 * @property Clienteopcionhorario[] $clienteopcionhorarios
 * @property Horarioseleccion $idHorarioSeleccion0
 */
abstract class BaseOpcionhorario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'opcionhorario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Opcionhorario|Opcionhorarios', $n);
	}

	public static function representingColumn() {
		return 'Hora';
	}

	public function rules() {
		return array(
			array('Hora, idHorarioSeleccion, Fecha', 'required'),
			array('idHorarioSeleccion', 'numerical', 'integerOnly'=>true),
			array('idOpcionHorario, Hora, idHorarioSeleccion, Fecha', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clienteopcionhorarios' => array(self::HAS_MANY, 'Clienteopcionhorario', 'idOpcionHorario'),
			'idHorarioSeleccion0' => array(self::BELONGS_TO, 'Horarioseleccion', 'idHorarioSeleccion'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idOpcionHorario' => Yii::t('app', 'Id Opcion Horario'),
			'Hora' => Yii::t('app', 'Hora'),
			'idHorarioSeleccion' => null,
			'Fecha' => Yii::t('app', 'Fecha'),
			'clienteopcionhorarios' => null,
			'idHorarioSeleccion0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idOpcionHorario', $this->idOpcionHorario);
		$criteria->compare('Hora', $this->Hora, true);
		$criteria->compare('idHorarioSeleccion', $this->idHorarioSeleccion);
		$criteria->compare('Fecha', $this->Fecha, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}