<?php

/**
 * This is the model base class for the table "pagos_estados".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PagosEstados".
 *
 * Columns in table "pagos_estados" available as properties of the model,
 * followed by relations of table "pagos_estados" available as properties of the model.
 *
 * @property integer $id
 * @property string $estado
 *
 * @property Pagos[] $pagoses
 */
abstract class BasePagosEstados extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pagos_estados';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PagosEstados|PagosEstadoses', $n);
	}

	public static function representingColumn() {
		return 'estado';
	}

	public function rules() {
		return array(
			array('estado', 'required'),
			array('estado', 'length', 'max'=>10),
			array('id, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pagoses' => array(self::HAS_MANY, 'Pagos', 'idEstado'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estado' => Yii::t('app', 'Estado'),
			'pagoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estado', $this->estado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}