<?php

/**
 * This is the model base class for the table "telefono".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Telefono".
 *
 * Columns in table "telefono" available as properties of the model,
 * followed by relations of table "telefono" available as properties of the model.
 *
 * @property integer $IDTelefono
 * @property integer $IDUsuario
 * @property string $Telefono
 * @property string $Tipo
 *
 * @property Usuario $iDUsuario
 */
abstract class BaseTelefono extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'telefono';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Telefono|Telefonos', $n);
	}

	public static function representingColumn() {
		return 'Telefono';
	}

	public function rules() {
		return array(
			array('IDUsuario, Telefono, Tipo', 'required'),
			array('IDUsuario', 'numerical', 'integerOnly'=>true),
			array('Telefono', 'length', 'max'=>12),
			array('Tipo', 'length', 'max'=>10),
			array('IDTelefono, IDUsuario, Telefono, Tipo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'iDUsuario' => array(self::BELONGS_TO, 'Usuario', 'IDUsuario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'IDTelefono' => Yii::t('app', 'Idtelefono'),
			'IDUsuario' => null,
			'Telefono' => Yii::t('app', 'Telefono'),
			'Tipo' => Yii::t('app', 'Tipo'),
			'iDUsuario' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('IDTelefono', $this->IDTelefono);
		$criteria->compare('IDUsuario', $this->IDUsuario);
		$criteria->compare('Telefono', $this->Telefono, true);
		$criteria->compare('Tipo', $this->Tipo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}