<?php

/**
 * This is the model base class for the table "clienteopcionhorario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Clienteopcionhorario".
 *
 * Columns in table "clienteopcionhorario" available as properties of the model,
 * followed by relations of table "clienteopcionhorario" available as properties of the model.
 *
 * @property integer $idClienteOpcionHorario
 * @property integer $idCliente
 * @property integer $idOpcionHorario
 *
 * @property Opcionhorario $idOpcionHorario0
 * @property Cliente $idCliente0
 */
abstract class BaseClienteopcionhorario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'clienteopcionhorario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Clienteopcionhorario|Clienteopcionhorarios', $n);
	}

	public static function representingColumn() {
		return 'idClienteOpcionHorario';
	}

	public function rules() {
		return array(
			array('idCliente, idOpcionHorario', 'required'),
			array('idCliente, idOpcionHorario', 'numerical', 'integerOnly'=>true),
			array('idClienteOpcionHorario, idCliente, idOpcionHorario', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idOpcionHorario0' => array(self::BELONGS_TO, 'Opcionhorario', 'idOpcionHorario'),
			'idCliente0' => array(self::BELONGS_TO, 'Cliente', 'idCliente'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idClienteOpcionHorario' => Yii::t('app', 'Id Cliente Opcion Horario'),
			'idCliente' => null,
			'idOpcionHorario' => null,
			'idOpcionHorario0' => null,
			'idCliente0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idClienteOpcionHorario', $this->idClienteOpcionHorario);
		$criteria->compare('idCliente', $this->idCliente);
		$criteria->compare('idOpcionHorario', $this->idOpcionHorario);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}