<?php

/**
 * This is the model base class for the table "pagos_bancos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PagosBancos".
 *
 * Columns in table "pagos_bancos" available as properties of the model,
 * followed by relations of table "pagos_bancos" available as properties of the model.
 *
 * @property integer $id
 * @property string $banco
 *
 * @property Pagos[] $pagoses
 */
abstract class BasePagosBancos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pagos_bancos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PagosBancos|PagosBancoses', $n);
	}

	public static function representingColumn() {
		return 'banco';
	}

	public function rules() {
		return array(
			array('banco', 'required'),
			array('banco', 'length', 'max'=>60),
			array('id, banco', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pagoses' => array(self::HAS_MANY, 'Pagos', 'idbanco'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'banco' => Yii::t('app', 'Banco'),
			'pagoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('banco', $this->banco, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}