<?php

/**
 * This is the model base class for the table "gasto_historial".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GastoHistorial".
 *
 * Columns in table "gasto_historial" available as properties of the model,
 * followed by relations of table "gasto_historial" available as properties of the model.
 *
 * @property integer $idGastoHistorial
 * @property integer $idGastoFecha
 * @property integer $idGasto
 * @property integer $Precio
 *
 * @property GastoEntidadHistorial[] $gastoEntidadHistorials
 * @property GastoFecha $idGastoFecha0
 * @property Gasto $idGasto0
 * @property PagosHistorialUsuario[] $pagosHistorialUsuarios
 */
abstract class BaseGastoHistorial extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gasto_historial';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GastoHistorial|GastoHistorials', $n);
	}

	public static function representingColumn() {
		return 'idGastoHistorial';
	}

	public function rules() {
		return array(
			array('idGastoFecha, idGasto, Precio', 'required'),
			array('idGastoFecha, idGasto, Precio', 'numerical', 'integerOnly'=>true),
			array('idGastoHistorial, idGastoFecha, idGasto, Precio', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'gastoEntidadHistorials' => array(self::HAS_MANY, 'GastoEntidadHistorial', 'idGastoHistorial'),
			'idGastoFecha0' => array(self::BELONGS_TO, 'GastoFecha', 'idGastoFecha'),
			'idGasto0' => array(self::BELONGS_TO, 'Gasto', 'idGasto'),
			'pagosHistorialUsuarios' => array(self::HAS_MANY, 'PagosHistorialUsuario', 'idGastoHistorial'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idGastoHistorial' => Yii::t('app', 'Id Gasto Historial'),
			'idGastoFecha' => null,
			'idGasto' => null,
			'Precio' => Yii::t('app', 'Precio'),
			'gastoEntidadHistorials' => null,
			'idGastoFecha0' => null,
			'idGasto0' => null,
			'pagosHistorialUsuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idGastoHistorial', $this->idGastoHistorial);
		$criteria->compare('idGastoFecha', $this->idGastoFecha);
		$criteria->compare('idGasto', $this->idGasto);
		$criteria->compare('Precio', $this->Precio);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}