<?php

/**
 * This is the model base class for the table "horarioseleccion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Horarioseleccion".
 *
 * Columns in table "horarioseleccion" available as properties of the model,
 * followed by relations of table "horarioseleccion" available as properties of the model.
 *
 * @property integer $idHorarioSeleccion
 * @property integer $idSeleccion
 *
 * @property Seleccion $idSeleccion0
 * @property Opcionhorario[] $opcionhorarios
 */
abstract class BaseHorarioseleccion extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'horarioseleccion';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Horarioseleccion|Horarioseleccions', $n);
    }

    public static function representingColumn() {
        return 'idHorarioSeleccion';
    }

    public function rules() {
        return array(
            array('idSeleccion', 'required'),
            array('idSeleccion', 'numerical', 'integerOnly' => true),
            array('idHorarioSeleccion, idSeleccion', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'idSeleccion0' => array(self::BELONGS_TO, 'Seleccion', 'idSeleccion'),
            'opcionhorarios' => array(self::HAS_MANY, 'Opcionhorario', 'idHorarioSeleccion'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'idHorarioSeleccion' => Yii::t('app', 'Id Horario Seleccion'),
            'idSeleccion' => null,
            'idSeleccion0' => null,
            'opcionhorarios' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('idHorarioSeleccion', $this->idHorarioSeleccion);
        $criteria->compare('idSeleccion', $this->idSeleccion);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
