<?php

/**
 * This is the model base class for the table "pagos_tipos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PagosTipos".
 *
 * Columns in table "pagos_tipos" available as properties of the model,
 * followed by relations of table "pagos_tipos" available as properties of the model.
 *
 * @property integer $id
 * @property string $tipo
 *
 * @property Pagos[] $pagoses
 */
abstract class BasePagosTipos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pagos_tipos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PagosTipos|PagosTiposes', $n);
	}

	public static function representingColumn() {
		return 'tipo';
	}

	public function rules() {
		return array(
			array('tipo', 'required'),
			array('tipo', 'length', 'max'=>20),
			array('id, tipo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pagoses' => array(self::HAS_MANY, 'Pagos', 'idtipo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tipo' => Yii::t('app', 'Tipo'),
			'pagoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('tipo', $this->tipo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}